<div class="card mb-3">
	<img class="card-img-top" src="images/<?= $articles_details["image"]?>">
	<div class="card-body">
		<h5 class="card-title">
			<?= $articles_details["titre"] ?>
		</h5>
		<p class="card-text">
			<?= $articles_details["contenu"]?>
		</p>
		<p class="cat">
			#
			<?= $articles_details["nomCat"]?>
		</p>
		<p class="card-text">
			<small class="text-muted">
				<?= $articles_details["date"] ?>
				<?= $articles_details["nom"] ?>
				<?= $articles_details["prenom"] ?>
			</small>
		</p>
	</div>
</div>
<div>
	<h2 class="blanc">Commentaires</h2>
</div>
<?php if(empty($commentaires)) : ?>
<p class="blanc">
	 soyez le premier à laissé un commentaire sur cette article 
</p>
<?php else: ?>
<?php foreach($commentaires as  $commentaire) : ?>
<div class="card">
	<div class="card-header" id ="comm">
		<p>
			<?= $commentaire["pseudo"] ?>
		</p>
	</div>
	<div class="card-body">
		<p class="card-text">
			<?= $commentaire["contenu"] ?>
		</p>
	</div>
	<small class="text-muted" id="smallCom">
		<p>
			<?= $commentaire["date"] ?>
		</p>
	</small>
</div>
<?php endforeach; ?>
<?php endif; ?>
<form action="ajout_comment.php" method="post">
	<h4 class="blanc">Ajouter un commentaire</h4>
	<fieldset>
		<div class="pseudo">
			<label for="story" class="blanc">Pseudo</label>
			<input type="text" name="pseudo"/>
		</div>
		<div>
			<textarea id="story" name="commentaire" rows="5" cols="100"></textarea>
		</div>
		<input type="hidden" name="id_article" value="<?= $id ?>"/>
		<input class="valider" type="submit" value="valider"/>
	</fieldset>
</form>
